### ISSUE TITLE
Make it compatible with arrays by replacing s.charAt(i) with s[i]

### ISSUE THREAD

**Issue by caub** [jhchen/fast-diff#15]
I'll try and see

also substring -> slice

**Comment by caub** [comment]
I'm investigating with other libs for now: fast-array-diff and fast-myers-diff which are compatible with both strings and arrays

**Comment by DennisTheMenace780** [comment]
@caub Do you happen to recall why this was failing for you? We might've ran into a similar problem but we don't have enough information here.

**Comment by caub** [comment]
@DennisTheMenace780 `fastDiff(['a', 'b'], ['a', 'c'])` used to fail
