### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ajkl2533** [jhchen/fast-diff#7]
Hi guys,
would you mind to add `LICENSE.md` file inside the repo root? Apache 2.0 requires to distribute license text along the source code and now there is none in repo and npm package, so it means that this code cannot be legally used by anyone.

So if you have a few minutes to add this https://www.apache.org/licenses/LICENSE-2.0 to the repository and release new patch version with the license, it would be really great.

Thank you

**Comment by char0n** [comment]
@ajkl2533 license in directly in [source code](https://github.com/jhchen/fast-diff/blob/master/diff.js#L10) and APACHE license allows URL instead of full license text. So we should be fine here.
